# SPDX-License-Identifier: GPL-2.0
# Keyboard Driver for Blackberry Keyboards BBQ10 from arturo182. Software written by wallComputer.


KERN_VER = $(shell uname -r)
KDIR ?= /lib/modules/$(KERN_VER)/build
MODULE_NAME := nvkbd
KBUILD_OUTPUT = build

obj-m := $(MODULE_NAME).o

$(MODULE_NAME)-objs:= src/mod_src/$(MODULE_NAME)_main.o src/mod_src/$(MODULE_NAME)_i2cHelper.o
ccflags-y := -I$(src)/src/mod_src/

